services:
  frontend:
    build:
      context: ./Dashboard-app
    container_name: app-container
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./Ascendion.Products.Dashboard.Api/Ascendion.Products.Dashboard.Api
    container_name: api-container
    ports:
      - "5000:80"
    # volumes:
    #   - ./Ascendion.Products.Dashboard.Api/Ascendion.Products.Dashboard.Api/app.db:/app/app.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AscendionDb;User Id=SA;Password=TonyStark@123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    # networks:
    #   - my-bridge-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD:"TonyStark@123"
      - ACCEPT_EULA:"Y"

    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
